<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <!--
    Section: properties details
    -->
    <groupId>com.github.livreprogramacao.restaurante.cozinha</groupId>
    <version>0.0.1</version>
    <artifactId>restaurante</artifactId>
    <name>Um restaunte composto de módulos independentes</name>
    <description>
        Visão geral
        Restaurante modular composto por unidades funcionais independentes (módulos) que se conectam fisicamente e operacionalmente para formar o empreendimento. Cada módulo tem responsabilidades claras, fluxos de trabalho definidos e interfaces padronizadas com os demais (espacial, elétrico, hidráulico e de informação).
    </description>
    <url>https://github.com/livreprogramacao/software-engineer-roadmap</url>
    <licenses>
        <!--
        Section: licenses details
        -->
        <license>
            <name>The Apache License, Version 2.0</name>
            <url>http://www.apache.org/licenses/LICENSE-2.0.txt</url>
            <distribution>repo</distribution>
            <comments>A permissive license allowing the software to be used freely.</comments>
        </license>
        <license>
            <name>MIT License</name>
            <url>https://opensource.org/licenses/MIT</url>
            <distribution>repo</distribution>
            <comments>A simple and easy-to-understand license.</comments>
        </license>
    </licenses>
    <developers>
        <!--
        Section: developers details
        -->
        <developer>
            <id>john.doe</id>
            <name>Fabio Santos Almeida</name>
            <email>livre.programacao@gmail.com</email>
            <url>https://github.com/livreprogramacao</url>
            <organization>Github Corp</organization>
            <organizationUrl>https://github.com/livreprogramacao</organizationUrl>
            <roles>
                <role>lead</role>
                <role>developer</role>
            </roles>
            <timezone>UTC-3</timezone>
        </developer>
        <developer>
            <id>basil.nigger</id>
            <name>Basil Nigger</name>
            <email>basil.nigger@gmail.com</email>
            <url>http://basil.nigger.com</url>
            <organization>Nigger Solutions</organization>
            <organizationUrl>https://github.com/livreprogramacao</organizationUrl>
            <roles>
                <role>developer</role>
                <role>tester</role>
            </roles>
            <timezone>UTC-3</timezone>
        </developer>
    </developers>
    <scm>
        <!--
        Section: scm details
        -->
        <connection>scm:git:git://github.com/livreprogramacao/software-engineer-roadmap.git</connection>
        <developerConnection>scm:git:ssh://github.com/livreprogramacao/software-engineer-roadmap.git</developerConnection>
        <tag>v0.0.1</tag>
        <url>https://github.com/livreprogramacao/software-engineer-roadmap</url>
    </scm>
    <properties>
        <!--
        Section: properties details
        -->
        <h2.version>2.4.240</h2.version>
        <hibernate.core.version>5.4.32.Final</hibernate.core.version>
        <jakarta.version>10.0.0</jakarta.version>
        <jakarta.ws.rs.api.version>3.1.0</jakarta.ws.rs.api.version>
        <jakartaee-api.version>11.0.0</jakartaee-api.version>
        <java.version>25</java.version>
        <javax.persistence.api.version>2.2</javax.persistence.api.version>
        <junit.jupiter.version>5.10.0</junit.jupiter.version>
        <liberty-plugin.version>3.10.3</liberty-plugin.version>
        <log4j.version>2.14.1</log4j.version>
        <lombok.version>1.18.42</lombok.version>
        <main.class>com.github.livreprogramacao.restaurante.cozinha.App</main.class> <!-- Define your main class here -->
        <mapstruct.version>1.6.3</mapstruct.version>
        <maven.compiler.source>${java.version}</maven.compiler.source>
        <maven.compiler.target>${java.version}</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.report.sourceEncoding>UTF-8</project.report.sourceEncoding>
        <slf4j.api.version>1.7.36</slf4j.api.version>
    </properties>
    <dependencies>
        <!--
        Section: dependencies details
        -->
        <dependency>
            <!-- Jakarta web -->
            <groupId>jakarta.ws.rs</groupId>
            <artifactId>jakarta.ws.rs-api</artifactId>
            <version>${jakarta.ws.rs.api.version}</version>
        </dependency>
        <dependency>
            <groupId>jakarta.servlet</groupId>
            <artifactId>jakarta.servlet-api</artifactId>
            <version>6.1.0</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>jakarta.inject</groupId>
            <artifactId>jakarta.inject-api</artifactId>
            <version>2.0.1</version>
        </dependency>
        <dependency>
            <groupId>jakarta.annotation</groupId>
            <artifactId>jakarta.annotation-api</artifactId>
            <version>3.0.0</version>
        </dependency>
        <dependency>
            <groupId>org.glassfish.jersey.containers</groupId>
            <artifactId>jersey-container-servlet-core</artifactId>
            <version>3.1.0</version>
        </dependency>
        <!--
                <dependency>
                    <groupId>javax.servlet</groupId>
                    <artifactId>jersey-media-servlet</artifactId>
                    <version>4.0.1</version>
                </dependency>
        -->
        <dependency>
            <groupId>org.glassfish.jersey.inject</groupId>
            <artifactId>jersey-hk2</artifactId>
            <version>3.1.0</version>
        </dependency>
        <dependency>
            <!-- Mapstruct -->
            <groupId>org.mapstruct</groupId>
            <artifactId>mapstruct</artifactId>
            <version>${mapstruct.version}</version>
        </dependency>
        <dependency>
            <groupId>org.mapstruct</groupId>
            <artifactId>mapstruct-processor</artifactId>
            <version>${mapstruct.version}</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <!-- Jakarta Validator -->
            <groupId>jakarta.validation</groupId>
            <artifactId>jakarta.validation-api</artifactId>
            <version>2.0.2</version>
        </dependency>
        <dependency>
            <!-- SLF4J API -->
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
            <version>${slf4j.api.version}</version> <!-- Use the latest version -->
        </dependency>
        <dependency>
            <!-- SLF4J Implementation -->
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-log4j12</artifactId>
            <version>${slf4j.api.version}</version> <!-- Log4j binding -->
        </dependency>
        <dependency>
            <!-- Lombok set up -->
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>${lombok.version}</version> <!-- Check for the latest version -->
            <scope>compile</scope>
        </dependency>
        <dependency>
            <!-- JPA Dependency -->
            <groupId>javax.persistence</groupId>
            <artifactId>javax.persistence-api</artifactId>
            <version>${javax.persistence.api.version}</version>
        </dependency>
        <dependency>
            <!-- JPA Implementation (Hibernate) -->
            <groupId>org.hibernate</groupId>
            <artifactId>hibernate-core</artifactId>
            <version>${hibernate.core.version}</version>
        </dependency>
        <dependency>
            <!-- H2 Database Dependency -->
            <groupId>com.h2database</groupId>
            <artifactId>h2</artifactId>
            <version>${h2.version}</version>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <!-- Testing -->
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-engine</artifactId>
            <version>${junit.jupiter.version}</version>
            <scope>test</scope>
        </dependency>
    </dependencies>
    <build>
        <!--
        Section: build
        The <build> section is essential for defining how your project should be compiled, packaged, and tested.
        This section enables you to configure various plugins crucial for building your application effectively.
        Proper configuration of this section can optimize your build process and streamline development workflows.
        -->
        <plugins>
            <plugin>
                <!-- Apache Maven that is used to compile the source code of a project. -->
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.10.1</version>
                <configuration>
                    <source>${java.version}</source>
                    <target>${java.version}</target>
                    <encoding>UTF-8</encoding>
                    <annotationProcessorPaths>
                        <path>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                            <version>${lombok.version}</version>
                        </path>
                        <path>
                            <groupId>org.mapstruct</groupId>
                            <artifactId>mapstruct-processor</artifactId>
                            <version>${mapstruct.version}</version>
                        </path>
                    </annotationProcessorPaths>
                </configuration>
            </plugin>
        </plugins>
    </build>
    <profiles>
        <!--
        Section: profiles
        Using profiles to define properties
        -->
        <profile>
            <id>dev</id>
            <properties>
                <property name="database.url" value="jdbc:mysql://localhost:3306/devdb"/>
                <property name="database.username" value="devuser"/>
                <property name="database.password" value="devpassword"/>
            </properties>
        </profile>
        <profile>
            <id>prod</id>
            <properties>
                <property name="database.url" value="jdbc:mysql://prodhost:3306/prddb"/>
                <property name="database.username" value="prduser"/>
                <property name="database.password" value="prdpassword"/>
            </properties>
        </profile>
    </profiles>
</project>